import pygame

EVENT_RED_HIT = pygame.USEREVENT + 1
EVENT_YELLOW_HIT = pygame.USEREVENT + 2
EVENT_BULLET_OFFSCREEN = pygame.USEREVENT + 3
EVENT_SPACESHIP_DESTROYED = pygame.USEREVENT + 4
EVENT_SPACESHIP_HIT = pygame.USEREVENT + 5
